### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isEditorPanelOpened')

### ISSUE THREAD

**Issue by laneparton** [janw-me/disable-full-site-editing#2]
It looks like there might be an issue with https://github.com/janw-me/disable-full-site-editing/blob/main/src/disable-fse.js#L6 when you navigate to `/wp-admin/widgets.php`

WordPress Version: 6.0
Plugin: 1.1.2

```
Uncaught TypeError: Cannot read properties of null (reading 'isEditorPanelOpened')
    at disable-fse.js?ver=1.1.2:6:38
```

I'll collect more info and try to resolve this :)

**Comment by laneparton** [comment]
@janw-me I believe this can be resolved with [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

```
	if (wp.data.select("core/edit-post")?.isEditorPanelOpened("template")) {
```

**Comment by janw-me** [comment]
Hi :wave: 

Sorry for the late reply, it's summertime...
Thank you for finding this error and fixing it. I've accepted the fix and on top of it I've also excluded the script from being loaded on the widgets page.

Let me know if you find anything else.
