### ISSUE TITLE
theme_file_path seems to no longer be used in WordPress 6.2 breaking plugin

### ISSUE THREAD

**Issue by aplauche** [janw-me/disable-full-site-editing#4]
When using WordPress 6.2 the plugin no longer works to disable the full site editor. I believe the editor no longer uses the 'theme_file_path' hook to load in HTML templates breaking that piece of functionality.

Will look into what the new setup is, but flagging for now in case anyone else already knows what needs to be changed

**Comment by aplauche** [comment]
Disregard, verified still working on 6.2 was an issue with environment variables getting reset on my 6.2 install.

**Comment by janw-me** [comment]
Hi, sorry for the late reply.
I missed it, I've revised my email filter so that won't happen again....

Great to hear this wasn't a 6.2 issue. If you do have other questions of whatever let me know.
